export const students = [
  { name: "Abdul Rochim", role: "Member"},  
  { name: "Ardyan Ardasyah", role: "Ketua Kelas"},  
  { name: "Artaya Dwi Saputra", role: "Member"},  
  { name: "Atha Rifqi Ardhani", role: "Member"},  
  { name: "Deny Raka Fahriansyah", role: "Sekretaris"},  
  { name: "Dharul Ulum", role: "Member"},  
  { name: "Haris Zildan Anggara", role: "Bendahara"},  
  { name: "Hendry Bagus Prasetyo", role: "Member"},  
  { name: "Honco Sasongko", role: "Member"},  
  { name: "Iftizal Fazal Azrul", role: "Member"},  
  { name: "Kevin Husni Mustaqim", role: "Member"},  
  { name: "M. Aditia Putra", role: "Member"},  
  { name: "Mirzaa Maulana Putra", role: "Member"},  
  { name: "Moh. Effan Mabrur Mubarok", role: "Wakil Ketua Kelas"},  
  { name: "Mohammad Januar Zulkifli", role: "Member"},  
  { name: "M. Azriel Yaumaziham", role: "Member"},  
  { name: "M. Cello Baktiawan Putra", role: "Member"},  
  { name: "M. Davi Andika", role: "Member"},  
  { name: "M. Hafif Myuttaqien", role: "Sekretaris"},  
  { name: "M. Refan Raditya", role: "Member"},  
  { name: "M. Ridho Febrian", role: "Member"},  
  { name: "M. Rizky Putra Al Farizi", role: "Member"},  
  { name: "M. Zaimmudin Agus", role: "Member"},  
  { name: "Rachmad Dwi Akbar", role: "Member"},  
  { name: "Rifqi Akbar Fian Musyafa", role: "Bendahara"},  
  { name: "Satria Fitra Hermawan", role: "Member"},  
  { name: "Sultan Yasir Arafat", role: "Member"},  
  { name: "Thomas Evelin Noorin Ramadhan", role: "Member"},  
  { name: "Yudhistira Arya Gharista", role: "Member"},  
];